# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c1f79101990f537c94dcc58aa949efda182624caea91e47f3c6956ffdc5f08e32cffc3360d41056758a9f8c5a1390222e0767b85ae3b31cd08ab5b7dcf5a437

test:
  secret_key_base: 93fbd4e425eb6fd315ac631689260796974933c2124d63f03a8442d8efa2dafcc4b8aaa14e922b9b8d0a8506a13e399946b1b35cd01f60511fc2ca469142e8b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
